var res = {
	"alex":{
		"managers":[
			"MoneyManager","PerlScriptManager"
			,"HabitManager"
			,"TaskManager"
			,"TestManager"
			,"TimeManager"
			,"MiscUtilManager"
			,"ReportManager"
			,"GermanManager"
			,"GymManager"
		]
		,"loginmessage":[
			"Tesime"
		]
		,"restartmessage":[
			"restart message"
		]
		,"timezone":"JST"
	},
	"father":{
		"managers":[
			"MoneyManager"
		],
		"loginmessage":[
			"README:",
			"https://github.com/nailbiter/assistantbot/blob/master/READMEs/MoneyBot.rus.md"
		]
		,"timezone":"EET"
	}
};
console.log(JSON.stringify(res));
