var res = {
	alex:{
		managers:[
			"MoneyManager","PerlScriptManager",
			"HabitManager",
			"TaskManager",
			"TestManager",
			"TimeManager",
			"MiscUtilManager",
			"ReportManager",
			"GermanManager",
			"GymManager",
			"PowerManager",
			"BirthdayManager",
		]
		,"loginmessage":[
			"Tesime"
		]
		,"restartmessage":[
			"restart message"
		]
		,"timezone":"JST"
	},
	mariia:{
		managers:[
			"MoneyManager"
		],
		loginmessage:[
			"README:",
			"https://github.com/nailbiter/assistantbot/blob/master/READMEs/MoneyBot.rus.md"
		],
		timezone:"EET",
	},
	father:{
		managers:[
			"MoneyManager"
		],
		loginmessage:[
			"README:",
			"https://github.com/nailbiter/assistantbot/blob/master/READMEs/MoneyBot.rus.md"
		],
		timezone:"EET",
	},
};
console.log(JSON.stringify(res));
